title: Flask Project Template
description: A starter Flask, Jinja and SQLite project
author: Digital Technologies Dept.

# If development is true, guides will be shown
development: true
picotheme: azure
